### ISSUE TITLE
Boolean filter is not working

### ISSUE THREAD

**Issue by jesephan** [ChronicStone/vue-sweettools#5] opened 2023-09-25 13:38 UTC
Boolean filter is not working when falsey value is either null or empty

**Comment by ChronicStone** [comment] 2023-09-26 12:47
Can't reproduce this one.

Please provide miminal representation of the configuration of your table (Is it server-side / client-side, ...etc). Ideally, a Stackblitz minimal reproduction would be the best.

**Comment by jesephan** [comment] 2023-09-26 14:39
Here is the [sample schema](https://pastebin.com/NkYNrput) to show that booleanFilter is not working and here is the [video recording](https://www.dropbox.com/scl/fi/dtrx91sp1ucudv6lqjkc2/booleanfilterissue.mp4?rlkey=n4n9uwb53y4sdjqoldeiw8mzm&dl=0) as well

**Comment by ChronicStone** [comment] 2023-09-26 15:31
@jesephan  This issue has already been resolved with release of v0.4.0. Upgrade to the latest version & that should fix the issue. (Specify the lib vers. you're using when opening an issue might be useful as well)

**Comment by jesephan** [comment] 2023-09-28 04:06
up confirmed its fixed in v0.4.0. thanks!

**Comment by jesephan** [comment] 2023-09-28 04:28
Hi @ChronicStone I have to reopen this since there is new issue in the v0.4.0. So basically the filters only work if I have to click reset button first. There is no changes on the sample schema. Here is the [video recording](https://www.dropbox.com/scl/fi/988f35hwujowmcru0fc81/new-filters-issue.mp4?rlkey=3ujilmzwyd47kqsi48kpegl6n&dl=0) of the issue

**Comment by ChronicStone** [comment] 2023-09-28 10:49
@jesephan interesting, I think I know what the issue is, I'll be addressing this today

**Comment by jesephan** [comment] 2023-10-02 08:46
Hi @ChronicStone here is the [new recording](https://www.dropbox.com/scl/fi/gpdsbtq4ihsw8h2wb9le0/rc.mp4?rlkey=i67xzfrmpidg43ai6prmoj2pd&dl=0) with the devtools visible specially the session storage. there you can clearly see that the filter values was persisted but it does not reflect in the UI. The issue I stated above though is now resolve.

**Comment by ChronicStone** [comment] 2023-10-03 13:32
@jesephan Fixed with release `0.4.4`

**Closed as completed by ChronicStone** 2023-10-03 13:32 UTC
Labels: question
